### ISSUE TITLE
How do I remove the application of the application list

### ISSUE THREAD

**Issue by TimeStarRipple** [naver/pinpoint#2340]
#### Description

How do I remove the application of the application list
#### Environment

* Pinpoint version:
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):
Ubuntu14.04
web,collector 1.6.0-RC2
agent 1.6.0

**Comment by Xylus** [comment]
Hi @TimeStarRipple 
There's a bunch of admin APIs available for this kind of housekeeping stuff in [AdminController](https://github.com/naver/pinpoint/blob/master/web/src/main/java/com/navercorp/pinpoint/web/controller/AdminController.java).
The one you're looking for is `/admin/removeApplicationName` taking in `applicationName` as a request parameter.

Note that you'll have to pass in an additional parameter `password` to call these admin APIs. The value is the one you configured in [pinpoint-web.properties](https://github.com/naver/pinpoint/blob/master/web/src/main/resources/pinpoint-web.properties#L22).

**Comment by WCrazyStone** [comment]
http://10.168.16.115:28080/admin/removeApplicationName?applicationName=MyTestPP

HTTP Status 404 - /admin/removeApplicationName

type Status report

message /admin/removeApplicationName

description The requested resource is not available.

Apache Tomcat/8.0.36
 
Thanks

**Comment by Xylus** [comment]
I missed the `.pinpoint` extension from, sorry.
Fixed my comment above.

**Comment by angeloudy** [comment]
Is it possible to just remove one agentid? Because after I changed the agentId, the old one still shows on the inspector.

**Comment by koo-taejin** [comment]
@angeloudy 
you can to use following rest api 
`/admin/removeAgentId.pinpoint?applicationName=&agentId=`

**Comment by altiankur** [comment]
i am getting "Missing password"

**Comment by Rnic** [comment]
@altiankur  i am getting "Missing password" too, can u fix this?

**Comment by Xylus** [comment]
@Rnic 
Please refer to https://github.com/naver/pinpoint/wiki/FAQ#how-do-i-delete-application-name-andor-agent-id-from-hbase.

**Comment by Rnic** [comment]
@Xylus thank you for your help !

**Comment by gongjiang1** [comment]
> @Xylus thank you for your help !


Oh, I have the same problem as you. What is the initial password? I don't remember I set it。

**Comment by minwoo-jung** [comment]
@gongjiang1

```
Note that the value for the password parameter is what you defined admin.password property in pinpoint-web.properties. Leaving this blank will allow you to call admin APIs without the password parameter.
```

**Comment by gongjiang1** [comment]
> @gongjiang1
> 
> ```
> Note that the value for the password parameter is what you defined admin.password property in pinpoint-web.properties. Leaving this blank will allow you to call admin APIs without the password parameter.
> ```

thx

**Comment by YangYanYing** [comment]
> @altiankur i am getting "Missing password" too, can u fix this?

http://server:port/pinpoint-web-1.7.1/admin/removeApplicationName.pinpoint?applicationName=ACH-two&password=admin,  it works
