### ISSUE TITLE
Methods in certain traces are given out as - API-METADATA-NOT-FOUND 

### ISSUE THREAD

**Issue by varun-krishna** [naver/pinpoint#6816]
Version - pinpoint-collector-2.0.2

We are using the GRPC ports,  Certain methods in trace are given out as API-METADATA-NOT-FOUND.

@koo-taejin  @emeroad  We are aiming to get pinpoint to production in a weeks time would really help if some light is thrown on this issue.

**Comment by emeroad** [comment]
I recommend the 2.0.2 update.
Data retry fail bug has been fixed in 2.0.2
 - https://github.com/naver/pinpoint/issues/6662

API-META-DATA uses 9991 port
Check status of 9991 port

**Comment by varun-krishna** [comment]
We are using version 2.0.2. The agent is running on Google Kubernates Engine. We are using a TCP load balancer exposing ports 9991,9992,9993. Logs indicate the following :

(c.n.p.p.s.g.MetadataGrpcDataSender ) Error. request=apiId: 48 apiInfo: "com.google.gson.Gson.toJson(java.lang.Object src, java.lang.Appendable writer)" line: 657, cause=UNAVAILABLE: io exception

io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
2020-05-29 22:11:22 [INFO ](c.n.p.p.s.g.MetadataGrpcDataSender ) Error. request=apiId: 49 apiInfo: "com.google.gson.Gson.toJson(java.lang.Object src, java.lang.reflect.Type typeOfSrc, java.lang.Appendable writer)" line: 682, cause=UNAVAILABLE: io exception
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception.

Please find the screenshot below : 

<img width="1334" alt="Screenshot 2020-06-01 at 11 08 31 AM" src="https://user-images.githubusercontent.com/63715204/83379078-469afa00-a3f8-11ea-91ed-eebd9708b270.png">



We are moving to prod with the setup , but if we are not able to solve this problem we might have to look at other options. We have spent a lot of effort solving this problem. It would be great if @emeroad @koo-taejin  you could help us. A clear picture on this status would really us.

**Comment by dinesh4747** [comment]
I did same problem and finally changed from gRPC to Thrift with all TCP ports (9994/9995/9996 - tcp) and but still seeing the similar exception as below 

`/app/pinpoint-agent-2.0.2/logs # netstat -atulnp | grep 999
tcp        0      0 10.45.180.48:49998      10.45.67.209:15004      ESTABLISHED -
tcp        0      0 10.45.180.48:59990      10.45.197.233:15004     ESTABLISHED -
tcp        0      0 10.45.180.48:56032      10.148.6.169:9994       ESTABLISHED -
tcp        0      0 10.45.180.48:59996      10.45.153.33:15004      ESTABLISHED -
tcp        0      0 10.45.180.48:45742      10.148.6.169:9996       ESTABLISHED -
tcp        0      0 10.45.180.48:44162      10.148.6.169:9995       ESTABLISHED -
tcp        0      0 ::ffff:10.45.180.48:44160 ::ffff:10.148.6.169:9995 ESTABLISHED 20/java
tcp        0      0 ::ffff:10.45.180.48:56030 ::ffff:10.148.6.169:9994 ESTABLISHED 20/java
tcp        0      0 ::ffff:10.45.180.48:45740 ::ffff:10.148.6.169:9996 ESTABLISHED 20/java`


Agent logs - (application is running on container in google kubernetes engine/GKE and collector is deployed in google compute engine/GCE as a stateful VM for stability reasons)

`2020-06-01 19:59:45 [WARN ](.p.r.c.DefaultPinpointClientHandler) DefaultPinpointClientHandler@2755d705 exceptionCaught() occurred. state:NO
java.net.ConnectException: Connection refused: /10.148.6.169:9996
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

2020-06-01 19:59:45 [INFO ](.p.r.c.DefaultPinpointClientHandler) DefaultPinpointClientHandler@3301500b channelClosed() started.
2020-06-01 19:59:45 [WARN ](c.n.p.r.u.ClientFactoryUtils       ) tcp connect fail. remote:10.148.6.169/9994 try reconnect, retryCount:2
2020-06-01 19:59:45 [INFO ](.n.p.r.c.PinpointClientHandlerState) DefaultPinpointClientHandler@3301500b stateTo() completed. Socket state ch
2020-06-01 19:59:45 [WARN ](c.n.p.r.u.ClientFactoryUtils       ) change background tcp connect mode remote:10.148.6.169/9994
2020-06-01 19:59:45 [INFO ](c.n.p.r.c.PinpointClientHandshaker ) PinpointClientHandshaker@7561db12 handshakeAbort() started.
2020-06-01 19:59:45 [INFO ](c.n.p.r.c.PinpointClientHandshaker ) PinpointClientHandshaker@7561db12 unexpected state
2020-06-01 19:59:45 [INFO ](int-TcpDataSender(Default)-Executor) Pinpoint-TcpDataSender(Default)-Executor(15-0) started.
2020-06-01 19:59:45 [INFO ](c.n.p.p.c.p.s.TraceSamplerProvider ) new BasicTraceSampler()
2020-06-01 19:59:45 [INFO ](c.n.p.p.s.TcpDataSender@Default    ) request fail. request:com.navercorp.pinpoint.profiler.metadata.ApiMetaData
com.navercorp.pinpoint.rpc.PinpointSocketException: reconnecting...
        at com.navercorp.pinpoint.rpc.client.ReconnectStateClientHandler.newReconnectException(ReconnectStateClientHandler.java:85)
        at com.navercorp.pinpoint.rpc.client.ReconnectStateClientHandler.reconnectFailureFuture(ReconnectStateClientHandler.java:71)
        at com.navercorp.pinpoint.rpc.client.ReconnectStateClientHandler.request(ReconnectStateClientHandler.java:90)
        at com.navercorp.pinpoint.rpc.client.DefaultPinpointClient.request(DefaultPinpointClient.java:121)
        at com.navercorp.pinpoint.profiler.sender.TcpDataSender.doRequest(TcpDataSender.java:351)
        at com.navercorp.pinpoint.profiler.sender.TcpDataSender.doRequest(TcpDataSender.java:284)
        at com.navercorp.pinpoint.profiler.sender.TcpDataSender.doRequest(TcpDataSender.java:240)
        at com.navercorp.pinpoint.profiler.sender.TcpDataSender.sendPacket(TcpDataSender.java:211)
        at com.navercorp.pinpoint.profiler.sender.TcpDataSender$1.execute(TcpDataSender.java:118)
        at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.doExecute(AsyncQueueingExecutor.java:164)
        at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.doExecute(AsyncQueueingExecutor.java:94)
        at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.run(AsyncQueueingExecutor.java:77)
        at java.lang.Thread.run(Thread.java:748)


2020-06-01 19:59:55 [WARN ](c.n.p.p.s.RetryQueue               ) discard retry message(RetryMessage{retryCount=3, maxRetryCount=3, bytes=11
2020-06-01 19:59:55 [INFO ](c.n.p.p.s.TcpDataSender@Default    ) request fail. request:RetryMessage{retryCount=3, maxRetryCount=3, bytes=18
com.navercorp.pinpoint.rpc.PinpointSocketException: reconnecting...
        at com.navercorp.pinpoint.rpc.client.ReconnectStateClientHandler.newReconnectException(ReconnectStateClientHandler.java:85)
        at com.navercorp.pinpoint.rpc.client.ReconnectStateClientHandler.reconnectFailureFuture(ReconnectStateClientHandler.java:71)
        at com.navercorp.pinpoint.rpc.client.ReconnectStateClientHandler.request(ReconnectStateClientHandler.java:90)
        at com.navercorp.pinpoint.rpc.client.DefaultPinpointClient.request(DefaultPinpointClient.java:121)
        at com.navercorp.pinpoint.profiler.sender.TcpDataSender.doRequest(TcpDataSender.java:351)
        at com.navercorp.pinpoint.profiler.sender.TcpDataSender.doRequest(TcpDataSender.java:318)
        at com.navercorp.pinpoint.profiler.sender.TcpDataSender.access$500(TcpDataSender.java:55)
        at com.navercorp.pinpoint.profiler.sender.TcpDataSender$4.run(TcpDataSender.java:343)
        at org.jboss.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:556)
        at org.jboss.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:632)
        at org.jboss.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:369)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at java.lang.Thread.run(Thread.java:748)
2020-06-01 19:59:55 [WARN ](c.n.p.p.s.RetryQueue               ) discard retry message(RetryMessage{retryCount=3, maxRetryCount=3, bytes=18
2020-06-01 19:59:55 [INFO ](c.n.p.p.s.TcpDataSender@Default    ) request fail. request:RetryMessage{retryCount=3, maxRetryCount=3, bytes=55
com.navercorp.pinpoint.rpc.PinpointSocketException: reconnecting...
        at com.navercorp.pinpoint.rpc.client.ReconnectStateClientHandler.newReconnectException(ReconnectStateClientHandler.java:85)
        at com.navercorp.pinpoint.rpc.client.ReconnectStateClientHandler.reconnectFailureFuture(ReconnectStateClientHandler.java:71)
        at com.navercorp.pinpoint.rpc.client.ReconnectStateClientHandler.request(ReconnectStateClientHandler.java:90)
        at com.navercorp.pinpoint.rpc.client.DefaultPinpointClient.request(DefaultPinpointClient.java:121)
        at com.navercorp.pinpoint.profiler.sender.TcpDataSender.doRequest(TcpDataSender.java:351)
        at com.navercorp.pinpoint.profiler.sender.TcpDataSender.doRequest(TcpDataSender.java:318)
        at com.navercorp.pinpoint.profiler.sender.TcpDataSender.access$500(TcpDataSender.java:55)
        at com.navercorp.pinpoint.profiler.sender.TcpDataSender$4.run(TcpDataSender.java:343)
        at org.jboss.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:556)
        at org.jboss.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:632)
        at org.jboss.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:369)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at java.lang.Thread.run(Thread.java:748)
2020-06-01 19:59:55 [WARN ](c.n.p.p.s.RetryQueue               ) discard retry message(RetryMessage{retryCount=3, maxRetryCount=3, bytes=55
2020-06-01 19:59:55 [INFO ](c.n.p.p.s.TcpDataSender@Default    ) request fail. request:RetryMessage{retryCount=3, maxRetryCount=3, bytes=16
com.navercorp.pinpoint.rpc.PinpointSocketException: reconnecting...`

**Comment by dinesh4747** [comment]
@yjqg6666

**Comment by yjqg6666** [comment]
> DefaultPinpointClientHandler@2755d705 exceptionCaught() occurred. state:NO
> java.net.ConnectException: Connection refused: /10.148.6.169:9996

**Comment by dinesh4747** [comment]
Added the collector config (pinpoint-collector.properties) for additional context (Incase I have misconfigure collector)

pinpoint.zookeeper.address=10.148.6.116,10.148.6.91,10.148.6.100

# base data receiver config  ---------------------------------------------------------------------
collector.receiver.base.ip=0.0.0.0
collector.receiver.base.port=9994

# number of tcp worker threads
collector.receiver.base.worker.threadSize=8
# capacity of tcp worker queue
collector.receiver.base.worker.queueSize=1024
# monitoring for tcp worker
collector.receiver.base.worker.monitor=true

collector.receiver.base.request.timeout=3000
collector.receiver.base.closewait.timeout=3000
# 5 min
collector.receiver.base.ping.interval=300000
# 30 min
collector.receiver.base.pingwait.timeout=1800000


# stat receiver config  ---------------------------------------------------------------------
collector.receiver.stat.udp=false
collector.receiver.stat.udp.ip=0.0.0.0
collector.receiver.stat.udp.port=9995
collector.receiver.stat.udp.receiveBufferSize=4194304
## required linux kernel 3.9 & java 9+
collector.receiver.stat.udp.reuseport=false
## If not set, follow the cpu count automatically.
#collector.receiver.stat.udp.socket.count=1

# Should keep in mind that TCP transport load balancing is per connection.(UDP transport loadbalancing is per packet)
collector.receiver.stat.tcp=true
collector.receiver.stat.tcp.ip=0.0.0.0
collector.receiver.stat.tcp.port=9995

collector.receiver.stat.tcp.request.timeout=3000
collector.receiver.stat.tcp.closewait.timeout=3000
# 5 min
collector.receiver.stat.tcp.ping.interval=300000
# 30 min
collector.receiver.stat.tcp.pingwait.timeout=1800000

# number of udp statworker threads
collector.receiver.stat.worker.threadSize=8
# capacity of udp statworker queue
collector.receiver.stat.worker.queueSize=64
# monitoring for udp stat worker
collector.receiver.stat.worker.monitor=true


# span receiver config  ---------------------------------------------------------------------
collector.receiver.span.udp=false
collector.receiver.span.udp.ip=0.0.0.0
collector.receiver.span.udp.port=9996
collector.receiver.span.udp.receiveBufferSize=4194304
## required linux kernel 3.9 & java 9+
collector.receiver.span.udp.reuseport=false
## If not set, follow the cpu count automatically.
#collector.receiver.span.udp.socket.count=1


# Should keep in mind that TCP transport load balancing is per connection.(UDP transport loadbalancing is per packet)
collector.receiver.span.tcp=true
collector.receiver.span.tcp.ip=0.0.0.0
collector.receiver.span.tcp.port=9996

collector.receiver.span.tcp.request.timeout=3000
collector.receiver.span.tcp.closewait.timeout=3000
# 5 min
collector.receiver.span.tcp.ping.interval=300000
# 30 min
collector.receiver.span.tcp.pingwait.timeout=1800000

# number of udp statworker threads
collector.receiver.span.worker.threadSize=32
# capacity of udp statworker queue
collector.receiver.span.worker.queueSize=256
# monitoring for udp stat worker
collector.receiver.span.worker.monitor=true


# configure l4 ip address to ignore health check logs
# support raw address and CIDR address (Ex:10.0.0.1,10.0.0.1/24)
collector.l4.ip=

# change OS level read/write socket buffer size (for linux)
#sudo sysctl -w net.core.rmem_max=
#sudo sysctl -w net.core.wmem_max=
# check current values using:
#$ /sbin/sysctl -a | grep -e rmem -e wmem

# number of agent event worker threads
collector.agentEventWorker.threadSize=4
# capacity of agent event worker queue
collector.agentEventWorker.queueSize=1024

statistics.flushPeriod=1000

# -------------------------------------------------------------------------------------------------
# The cluster related options are used to establish connections between the agent, collector, and web in order to send/receive data between them in real time.
# You may enable additional features using this option (Ex : RealTime Active Thread Chart).
# -------------------------------------------------------------------------------------------------
# Usage : Set the following options for collector/web components that reside in the same cluster in order to enable this feature.
# 1. cluster.enable (pinpoint-web.properties, pinpoint-collector.properties) - "true" to enable
# 2. cluster.zookeeper.address (pinpoint-web.properties, pinpoint-collector.properties) - address of the ZooKeeper instance that will be used to manage the cluster
# 3. cluster.web.tcp.port (pinpoint-web.properties) - any available port number (used to establish connection between web and collector)
# -------------------------------------------------------------------------------------------------
# Please be aware of the following:
#1. If the network between web, collector, and the agents are not stable, it is advisable not to use this feature.
#2. We recommend using the cluster.web.tcp.port option. However, in cases where the collector is unable to establish connection to the web, you may reverse this and make the web establish connection to the collector.
#   In this case, you must set cluster.connect.address (pinpoint-web.properties); and cluster.listen.ip, cluster.listen.port (pinpoint-collector.properties) accordingly.
cluster.enable=true
cluster.zookeeper.address=10.148.6.116,10.148.6.91,10.148.6.100
cluster.zookeeper.sessiontimeout=30000
cluster.listen.ip=
cluster.listen.port=-1

#collector.admin.password=
#collector.admin.api.rest.active=
#collector.admin.api.jmx.active=

collector.spanEvent.sequence.limit=10000

# Flink configuration
flink.cluster.enable=true
flink.cluster.zookeeper.address=10.148.6.116,10.148.6.91,10.148.6.100
flink.cluster.zookeeper.sessiontimeout=3000

**Comment by varun-krishna** [comment]
@koo-taejin @emeroad @jaehong-kim @yjqg6666 

i am seeing the exception in collector , looks like it has something to do with issue . Can you please throw some light

<img width="1418" alt="Screenshot 2020-06-03 at 11 06 02 AM" src="https://user-images.githubusercontent.com/63715204/83599860-e12b4280-a58a-11ea-948b-e1df17e9bd93.png">

**Comment by dinesh4747** [comment]
Tried to get the output of netstat across all 3 collector instances (netstat -tnlp | grep 999)

All looks clean it's listening

tcp6       0      0 :::9991                 :::*                    LISTEN      3630/java
tcp6       0      0 :::9992                 :::*                    LISTEN      3630/java
tcp6       0      0 :::9993                 :::*                    LISTEN      3630/java
tcp6       0      0 :::9994                 :::*                    LISTEN      3630/java
tcp6       0      0 :::9995                 :::*                    LISTEN      3630/java
tcp6       0      0 :::9996                 :::*                    LISTEN      3630/java

**Comment by varun-krishna** [comment]
additionally posting the pinpoint-conifg we are using , and would really help if we get clarified if the config is fine. 

<img width="1276" alt="Screenshot 2020-06-03 at 11 55 00 AM" src="https://user-images.githubusercontent.com/63715204/83606739-b85d7a00-a597-11ea-96b8-9a7599f2a755.png">

**Comment by dinesh4747** [comment]
There were some inconsistencies around cluster enable so we have disabled cluster.enable=false and this stopped the exceptions from collector but agent was still throwing the below "Reconnecting"exceptions and subsequently "API_META_DATA_NOT_FOUND" still persists

2020-06-03 10:39:56 [INFO ](c.n.p.p.s.TcpDataSender@Default    ) request fail. request:com.navercorp.pinpoint.profiler.metadata.ApiMetaData
com.navercorp.pinpoint.rpc.PinpointSocketException: reconnecting...
        at com.navercorp.pinpoint.rpc.client.ReconnectStateClientHandler.newReconnectException(ReconnectStateClientHandler.java:85)
        at com.navercorp.pinpoint.rpc.client.ReconnectStateClientHandler.reconnectFailureFuture(ReconnectStateClientHandler.java:71)
        at com.navercorp.pinpoint.rpc.client.ReconnectStateClientHandler.request(ReconnectStateClientHandler.java:90)
        at com.navercorp.pinpoint.rpc.client.DefaultPinpointClient.request(DefaultPinpointClient.java:121)
        at com.navercorp.pinpoint.profiler.sender.TcpDataSender.doRequest(TcpDataSender.java:351)
        at com.navercorp.pinpoint.profiler.sender.TcpDataSender.doRequest(TcpDataSender.java:284)
        at com.navercorp.pinpoint.profiler.sender.TcpDataSender.doRequest(TcpDataSender.java:240)
        at com.navercorp.pinpoint.profiler.sender.TcpDataSender.sendPacket(TcpDataSender.java:211)
        at com.navercorp.pinpoint.profiler.sender.TcpDataSender$1.execute(TcpDataSender.java:118)
        at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.doExecute(AsyncQueueingExecutor.java:164)
        at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.doExecute(AsyncQueueingExecutor.java:94)
        at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.run(AsyncQueueingExecutor.java:77)
        at java.lang.Thread.run(Thread.java:748)
2020-06-03 10:39:56 [INFO ](c.n.p.p.s.TcpDataSender@Default    ) request fail. request:com.navercorp.pinpoint.profiler.metadata.ApiMetaData
com.navercorp.pinpoint.rpc.PinpointSocketException: reconnecting...
        at com.navercorp.pinpoint.rpc.client.ReconnectStateClientHandler.newReconnectException(ReconnectStateClientHandler.java:85)
        at com.navercorp.pinpoint.rpc.client.ReconnectStateClientHandler.reconnectFailureFuture(ReconnectStateClientHandler.java:71)
        at com.navercorp.pinpoint.rpc.client.ReconnectStateClientHandler.request(ReconnectStateClientHandler.java:90)
        at com.navercorp.pinpoint.rpc.client.DefaultPinpointClient.request(DefaultPinpointClient.java:121)
        at com.navercorp.pinpoint.profiler.sender.TcpDataSender.doRequest(TcpDataSender.java:351)
        at com.navercorp.pinpoint.profiler.sender.TcpDataSender.doRequest(TcpDataSender.java:284)
        at com.navercorp.pinpoint.profiler.sender.TcpDataSender.doRequest(TcpDataSender.java:240)
        at com.navercorp.pinpoint.profiler.sender.TcpDataSender.sendPacket(TcpDataSender.java:211)
        at com.navercorp.pinpoint.profiler.sender.TcpDataSender$1.execute(TcpDataSender.java:118)
        at com.navercorp.pinpoint.profiler.sender.DefaultAsyncQueueingExecutorListener.execute(DefaultAsyncQueueingExecutorListener.java:42
        at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.doExecute(AsyncQueueingExecutor.java:160)
        at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.doExecute(AsyncQueueingExecutor.java:87)
        at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.run(AsyncQueueingExecutor.java:77)
        at java.lang.Thread.run(Thread.java:748)

**Comment by dinesh4747** [comment]
Netstat output

netstat -atunlp | grep 999

====================================================================
tcp        0      0 10.45.10.160:44758      10.148.6.2:9994         ESTABLISHED -
tcp        0      0 10.45.10.160:36334      10.148.6.2:9996         ESTABLISHED -
tcp        0      0 10.45.10.160:33392      10.148.6.2:9995         ESTABLISHED -
tcp        0      0 ::ffff:10.45.10.160:44756 ::ffff:10.148.6.2:9994  ESTABLISHED 20/java
tcp        0      0 ::ffff:10.45.10.160:36332 ::ffff:10.148.6.2:9996  ESTABLISHED 20/java
tcp        0      0 ::ffff:10.45.10.160:33390 ::ffff:10.148.6.2:9995  ESTABLISHED 20/java

====================================================================

**Comment by varun-krishna** [comment]
getting connection refused exception : 

*******************************************************************************************
020-06-03 10:48:33 [WARN ](.p.r.c.DefaultPinpointClientHandler) DefaultPinpointClientHandler@2755d705 exceptionCaught() occurred. state:NONE. Caused:Connection refused: /10.148.6.2:9996
java.net.ConnectException: Connection refused: /10.148.6.2:9996
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-06-03 10:48:33 [WARN ](c.n.p.r.u.ClientFactoryUtils       ) tcp connect fail. remote:10.148.6.2/9996 try reconnect, retryCount:0
2020-06-03 10:48:33 [WARN ](.p.r.c.DefaultPinpointClientHandler) DefaultPinpointClientHandler@287f94b1 exceptionCaught() occurred. state:NONE. Caused:Connection refused: /10.148.6.2:9996
java.net.ConnectException: Connection refused: /10.148.6.2:9996
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by yjqg6666** [comment]
Pls run `telnet 10.148.6.2 9996` for connectivity.
